image_width: 2048
image_height: 1500
camera_name: mvch120_left
camera_matrix:
  rows: 3
  cols: 3
  data: [ 907.54488,    0.     , 1004.48243,
            0.     ,  907.82952,  761.75318,
            0.     ,    0.     ,    1.     ]
distortion_model: plumb_bob
distortion_coefficients:
  rows: 1
  cols: 5
  data: [-0.109578, 0.042257, -0.000970, 0.000274, 0.000000]
rectification_matrix:
  rows: 3
  cols: 3
  data: [1., 0., 0.,
         0., 1., 0.,
         0., 0., 1.]
projection_matrix:
  rows: 3
  cols: 4
  data: [ 871.74234,    0.     , 1008.36221,    0.     ,
            0.     ,  872.70803,  758.00656,    0.     ,
            0.     ,    0.     ,    1.     ,    0.     ]