<?xml version="1.0"?>
<package format="3">
  <name>usb_camera_bringup</name>
  <version>0.1.0</version>
  <description>Launch files for the RER USB global-shutter stereo camera.</description>
  <maintainer email="changxin@luxitech.cn">chang xin</maintainer>
  <license>Proprietary</license>

  <buildtool_depend>ament_cmake</buildtool_depend>
  <exec_depend>ament_index_python</exec_depend>
  <exec_depend>launch</exec_depend>
  <exec_depend>launch_ros</exec_depend>
  <exec_depend>tf2_ros</exec_depend>
  <exec_depend>usb_camera_driver</exec_depend>
  <exec_depend>yesense_std_ros2</exec_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
