[Unit]
Wants=network-online.target
After=network-online.target

[Service]
ExecStartPre=/bin/bash -c 'for i in {1..20}; do ip -4 -o addr show dev eth0 scope global | grep -q "inet 192.168.123.49/24" && exit 0; sleep 0.5; done; exit 1'
